version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "8080:8080"
    volumes:
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock
      - ../:/root/stsbmt:ro
    restart: always

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
